// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseForFFmpeg() {
  return window['go']['main']['App']['BrowseForFFmpeg']();
}

export function CancelGeneration() {
  return window['go']['main']['App']['CancelGeneration']();
}

export function DownloadFFmpeg() {
  return window['go']['main']['App']['DownloadFFmpeg']();
}

export function GeneratePanels(arg1) {
  return window['go']['main']['App']['GeneratePanels'](arg1);
}

export function GetFFmpegStatus() {
  return window['go']['main']['App']['GetFFmpegStatus']();
}

export function GetVideoInfo(arg1) {
  return window['go']['main']['App']['GetVideoInfo'](arg1);
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function OpenOutputFolder() {
  return window['go']['main']['App']['OpenOutputFolder']();
}

export function SavePanelsTo(arg1) {
  return window['go']['main']['App']['SavePanelsTo'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectOutputDir() {
  return window['go']['main']['App']['SelectOutputDir']();
}

export function SelectVideo() {
  return window['go']['main']['App']['SelectVideo']();
}
