// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BrowseForFFmpeg():Promise<string>;

export function CancelGeneration():Promise<void>;

export function DownloadFFmpeg():Promise<void>;

export function GeneratePanels(arg1:main.ProcessOptions):Promise<main.ProcessResult>;

export function GetFFmpegStatus():Promise<string>;

export function GetVideoInfo(arg1:string):Promise<main.VideoInfo>;

export function LoadSettings():Promise<main.Settings>;

export function OpenOutputFolder():Promise<void>;

export function SavePanelsTo(arg1:Array<string>):Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SelectOutputDir():Promise<string>;

export function SelectVideo():Promise<string>;
